### ISSUE TITLE
Parametri per metodo mrtdAuth()

### ISSUE THREAD

**Issue by 3F-ADMIN** [italia/cie-nis-python-sdk#19]
Buonasera, 
Io ho clonato il progetto e funziona tutto mettendo i dati all'interno del metodo in modo statico. Il mio problema sorge però quando devo manipolare i dati quando derivano da una vera smartcard. La interface si inizializza e rileva il NFC ma non capisco come risalire alle date e al numero di carta necessari per invocare il metodo!
Grazie mille in anticipo

**Comment by webartoli** [comment]
Stesso problema; seguendo la documentazione supponendo di avere:
- data nascita il 13 gennaio 1982
- scadenza 13 gennaio 2035
- numero carta `AB12345YZ`

l'invocazione corretta dovrebbe essere:

```py
  interface.mrtdAuth('820113', '350113', 'AB12345YZ')
```

ma lanciando il programma si ottiene:

```py
python .\main.py

                ██████╗██╗███████╗██████╗
               ██╔════╝██║██╔════╝╚════██╗
               ██║     ██║█████╗   █████╔╝
               ██║     ██║██╔══╝   ╚═══██╗
               ╚██████╗██║███████╗██████╔╝
                ╚═════╝╚═╝╚══════╝╚═════╝

Waiting for the CIE...
Connected!
Traceback (most recent call last):
  File "D:\cie\cie-nis-python-sdk\main.py", line 46, in <module>
    main()
    ~~~~^^
  File "D:\cie\cie-nis-python-sdk\main.py", line 25, in main
    interface.mrtdAuth('820113', '350113', 'AB12345YZ')
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\cie\cie-nis-python-sdk\pkg\lib\CIEInterface.py", line 174, in mrtdAuth
    raise Exception('CIEInterface.mrtdAuth: could not complete the authentication process')
Exception: CIEInterface.mrtdAuth: could not complete the authentication process
```

**Comment by areax99** [comment]
Stesso e identico problema...Qualcuno ha risolto?

**Comment by webartoli** [comment]
Vado a memoria perché è passato un pochino di tempo.

Mi pare che l’esempio dotnet funzionasse benone e da lì si riusciva a capire l’utilizzo atteso

**Comment by 3F-ADMIN** [comment]
Confermo quello che ha detto @webartoli 
L'esempio .NET funziona alla perfezione, dopo aver sistemato un paio di cose, e non ha bisogno di tutti quei campi, basta solo il codice CAN. 
Io lo sto utilizzando tutt'ora.
